SELECT IF(FC IS NULL,0,FC) AS FISH_COUNT,FISH_NAME
FROM FISH_NAME_INFO A RIGHT OUTER JOIN (SELECT FISH_TYPE,COUNT(*) AS FC
      FROM FISH_INFO
      GROUP BY FISH_TYPE) B ON A.FISH_TYPE=B.FISH_TYPE
ORDER BY FISH_COUNT DESC;