/*
SELECT TRUNCATE(PRICE,-4) AS PRICE_GROUP, COUNT(*) AS PRODUCTS
FROM PRODUCT
GROUP BY PRICE_GROUP
ORDER BY PRICE_GROUP ASC;
*/

SELECT PRICE_GROUP, COUNT(*) AS PRODUCTS
FROM (SELECT PRODUCT_ID, TRUNCATE(PRICE,-4) AS PRICE_GROUP
     FROM PRODUCT) AS A NATURAL JOIN PRODUCT AS B
GROUP BY PRICE_GROUP
ORDER BY PRICE_GROUP ASC;